config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'session#destroy'
  get 'sessions/new'

  namespace :admin do
    resources :users
  end

  resources :task1s

  root to: 'task1s#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task1.rb
class Task1 < ApplicationRecord
    before_validation :set_names_name
    validates :name, presence: true
    validates :name, length: {maximum: 30}
    validate :validate_name_not_including_comma

    berongs_to :user

    scope :recent, -> {order(createed_at: desc)}

    private 

    def set_names_name
        self.name = '名前なし' if name.blank?

    end

    # def validate_name_not_including_comma
    #     errors.add(:name, 'にカンマを含めることはできません')　if name&.include?(',')
    # end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true

    has_many :task1s
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: "#{@user.name}を登録しました"
    else
       render :new
    end
  end



  def edit

  end

  def show
  end

  def index
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)

  end

  def require_admin
    redirect_to root_url unless current_user.admin?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    before_action :login_required
    private

    def current_user
        @current_user ||=User.find_by(id: session[:user_id]) if session[:user_id]
    
    end

    def login_required
        redirect_to login_url unless current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  def new
  end

  def create 
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:email])
      session[:user_id] = user.id
      resirect_to root_url, notice: 'ログインした'
      
    else
      render :new
    end
  end

  def destrooy
    reset_session
    redirect_to root_url, notice: 'ログアウト'
  end

private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/task1s_controller.rb
class Task1sController < ApplicationController
  before_action :set_tasks, only:[:show, :edit, :update, :destroy]
  def index
    @tasks = current_user.task1s.recent
  end

  def show
  end

  def new
    @task = Task1.new
  end

  def edit

  end

  def update
    task.update!(task_params)
    redirect_to task1s_url, notice: "タスク#{task.name}を更新しました"
  end

  def create
    if @task.save
    redirect_to @task, notice: "タスク#{@task.name}を登録しました"
    else
      render :new
    end
    
  end

  def destroy
  task.destroy
  redirect_to task1s_url, notice: "タスクを削除しました"
end



  private

  def task_params
    params.require(:task1).permit(:name, :description)
  end

def set_tasks
   @task = current_user.task1s.find(params[:id])
end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/task1s_helper.rb
module Task1sHelper
end

app/views/admin/users/edit.html.slim
h1 Admin::Users#edit
p Find me in app/views/admin/users/edit.html.slim

app/views/admin/users/index.html.slim
h1 Admin::Users#index
p Find me in app/views/admin/users/index.html.slim

app/views/admin/users/new.html.slim
h1 ユーザー登録


/ = form_with model: [:admin, @user], local: true do |f|
/     .form-group 
/         =f.label :name
/         =f.text_field :name, class: 'form-control', id: 'task_name'

= form_with model: [:admin, @user], local: true do |f|
    .form-group
        =f.label :name
        =f.text_field :name, class: 'form-control'
    .form-group
        =f.label :email, class: 'form-control'
        =f.text_field :email, class: 'form-control'
    .form-check
        =f.label :admin, class: 'form-check-input' 
        =f.check_box :admin, class: 'form-check-input'
        |管理者権限
    
    .form-group
        =f.label :password
        =f.password_field :password, class: 'form-control'
    .form-group
        =f.label :password_confirmation, 'パスワード確認'
        =f.password_field :password_confirmation, class: 'form-control'
    =f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/show.html.slim
h1 Admin::Users#show
p Find me in app/views/admin/users/show.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Task
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
  .app-titl.navber.navbar-expand-md.navbar-light.bg-light
    .navbar-brand Task

ul.navbar-nav.ml-auto
  - if current_user
    li.nav-item= link_to 'タスク一覧', task_path, class: 'nav-link'
      -if current_user.admin?
        li.nav-item= link_to 'ユーザー一覧', admin_user_path, class: 'nav-link'
    li.nav-item= link_to 'ログアウト', logout_path, class: 'nav-link'
  -else
    li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
  .container  
    - if flash.notice.present?
      .alert.alert-success = flash.notice
    = yield

app/views/task1s/_form.html.slim
- if task.errors.present?
    UI#errors_explanation
     - task.errors.full_messages.each do |message|
      li= message

= form_with model: task, local: true do |f|
    .form-group 
        =f.label :name
        =f.text_field :name, class: 'form-control', id: 'task_name'

    .form-group
        =f.label :description
        =f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
    =f.submit nil, class: 'btn btn-primary'

app/views/task1s/edit.html.slim
h1 タスクの編集

.nav.justify-content-end
    = link_to '一覧', task1s_path, class: 'nav-link'

=render partial: 'form', locals: {task: @task}
    

app/views/task1s/index.html.slim
h1 タスク一覧
= link_to '新規登録', new_task1_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
    thead.thead-default
        tr
            th = Task1.human_attribute_name(:name)
            th = Task1.human_attribute_name(:cerated_at)
        tbody
            - @tasks.each do |task|
             tr
              td = link_to task.name, task1_path(task)
              td = task.created_at
              td
                = link_to '編集', edit_task1_path(task), class: 'btn btn-primary mr-3'
                = link_to '削除', task, method: :delete, data: {confirm: "タスク#{task.name}を削除します"}, 
                class: 'btn btn-danger'

app/views/task1s/new.html.slim
h1 タスクの新規一覧

.nav.justify-content-emd
    = link_to '一覧', task1s_path, class: 'nav-link'

= render partial: 'form', locals: {task: @task}

app/views/task1s/show.html.slim
h1 タスクの詳細

.nav.justify-content-end
 = link_to '一覧', task1s_path, class: 'nav-link'
 table.table.table-hover
  tbody
   tr
     th=Task1.human_attribute_name(:id)
     th=@task.id
   tr
     th=Task1.human_attribute_name(:name)
     td=@task.name
   tr
     th=Task1.human_attribute_name(:description)
     td = auto_link(simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: 'div'))
   tr
     th=Task1.human_attribute_name(:created_at)
     td=@task.created_at
   tr
     th=Task1.human_attribute_name(:updated_at)
     td=@task.updated_at

=link_to '削除', @task, method: :delete, data: {confirm: "タスク#{@task.name}を削除しましす"}, class: 'btn btn-danger'

   